import { mediaFull, escapeHtml } from "../layout.js";

const FRONT_ENDS = [
  { key: "customer", title: "Customer App", accent: "navy", body: "A driver-facing experience for starting a service journey, following progress and staying connected across handoffs." },
  { key: "diagnostic", title: "Diagnostic App", accent: "teal", body: "A diagnostic-facing workspace for receiving vehicle context, documenting findings and handing the vehicle into the next appropriate service step." },
  { key: "shop", title: "Shop Partner App", accent: "gold", body: "A repair-shop interface for managing incoming work, customer communication and coordinated service handoffs." },
  { key: "vendor", title: "Parts Vendor App", accent: "navy", body: "A parts-facing experience supporting availability, fulfilment and connection to active service journeys." },
  { key: "tow", title: "Tow Truck App", accent: "teal", body: "A transport-facing interface for coordinated vehicle pickup, movement and delivery into the service network." }
];

const PARTNER_TYPES = [
  { title: "Dealerships", accent: "navy", cta: "Explore Dealership Partnerships", body: "Connect dealership service, diagnostics and customer support into the wider ROVIQ journey." },
  { title: "Diagnostic Partners", accent: "teal", cta: "Become a Diagnostic Partner", body: "Participate as an independent diagnostic node that can help determine the next service step." },
  { title: "Repair & Service Providers", accent: "gold", cta: "Join as a Repair Partner", body: "Receive coordinated service opportunities and keep customers connected through the repair process." },
  { title: "Vehicle Transport & Towing", accent: "navy", cta: "Partner for Transport", body: "Move vehicles between customers, diagnostics, shops and other service locations as part of one connected journey." },
  { title: "Mobility Providers", accent: "teal", cta: "Explore Mobility Partnerships", body: "Support customers with practical mobility options while their vehicle is unavailable." }
];

export function roviqPage(c) {
  return `
<section class="hero section--tight"><div class="container"><div class="grid grid--2" style="align-items:center;"><div><span class="eyebrow">Automotive service coordination</span><h1>${escapeHtml(c["roviq.hero_heading"] || "One engine behind the automotive journey")}</h1><p class="lead">ROVIQ connects vehicle owners, diagnostics, repair, parts, towing, mobility and physical infrastructure through one coordinated platform.</p><p class="lead"><strong>Multiple front ends. One coordinated backend. One ROVIQ engine.</strong></p></div><div style="text-align:center;"><img src="/brand/roviq-lockup.png" alt="Roviq — Stations, Fleet, Parts, People." style="max-width:280px;width:100%;margin:0 auto;border-radius:12px;"></div></div></div></section>

<section class="section section--cream-alt"><div class="container"><span class="eyebrow">How it works</span><h2>One connected journey across multiple automotive participants.</h2><div class="grid grid--3"><div class="card card--accent-navy"><h3>1. Start</h3><p>The customer begins with a need, question or vehicle issue.</p></div><div class="card card--accent-teal"><h3>2. Coordinate</h3><p>ROVIQ keeps the relevant service participants connected as the vehicle moves through the journey.</p></div><div class="card card--accent-gold"><h3>3. Resolve</h3><p>The customer stays connected through diagnosis, repair, transport, parts and return-to-road steps.</p></div></div></div></section>

<section class="section" id="shop"><div class="container"><span class="eyebrow">One backend, five doors in</span><h2>Role-based front ends</h2><div class="grid grid--3">${FRONT_ENDS.map((f)=>`<div class="card card--accent-${f.accent}"><h3>${f.title}</h3><p>${escapeHtml(f.body)}</p></div>`).join("\n")}</div><div class="roviq-app-showcase"><div class="roviq-app-frame">${mediaFull("/images/Roviq AI Auto Service Dashboard.png","Roviq AI auto service dashboard concept")}</div><div class="roviq-app-frame">${mediaFull("/images/Roviq Smart Mobility Network Mockup.png","Roviq smart mobility network app concept")}</div></div><p class="roviq-app-caption">Selected interface concepts show the product direction without publishing internal routing logic, scoring, decision rules or proprietary data architecture.</p></div></section>

<section class="section section--cream-alt"><div class="container"><span class="eyebrow">Diagnostics</span><h2>Diagnostics as a connected entry point, not a dead end.</h2><p class="lead">ROVIQ can connect diagnostic providers into the wider service journey so findings can move forward with the vehicle instead of being isolated from the next repair, parts or transport step.</p><div class="grid grid--3"><div class="card card--accent-teal"><h3>Vehicle context</h3><p>Keep the customer and vehicle connected to the diagnostic visit.</p></div><div class="card card--accent-navy"><h3>Clear handoff</h3><p>Move from diagnostic findings into the appropriate next service action.</p></div><div class="card card--accent-gold"><h3>Partner visibility</h3><p>Give participating service providers the context needed for a smoother handoff.</p></div></div></div></section>

<section class="section"><div class="container"><span class="eyebrow">Repair shops & service providers</span><h2>Bring independent shops into the same coordinated experience.</h2><p class="lead">ROVIQ is designed to work with existing automotive businesses rather than replacing them. Shops remain independent while gaining a connected path into customer, diagnostic, parts and transport journeys.</p><div class="grid grid--3"><div class="card card--accent-gold"><h3>Incoming work</h3><p>Receive service opportunities with clearer customer and vehicle context.</p></div><div class="card card--accent-teal"><h3>Connected communication</h3><p>Keep the customer informed as the service journey progresses.</p></div><div class="card card--accent-navy"><h3>Network handoffs</h3><p>Coordinate with diagnostics, parts and transport when the job requires more than one participant.</p></div></div></div></section>

<section class="section section--cream-alt"><div class="container"><span class="eyebrow">Dealerships</span><h2>A dealership-facing path into the same ecosystem.</h2><p class="lead">Dealership service departments can participate as high-capability service nodes while keeping their own customer relationships, processes and brand experience.</p><p>ROVIQ can support dealership service journeys, diagnostic escalation, customer communication and coordinated external handoffs without exposing internal dealership systems or proprietary ROVIQ decision logic.</p></div></section>

<section class="section section--navy"><div class="container"><span class="eyebrow">Connected handoffs</span><h2>From request to resolution without losing the thread.</h2><p class="lead">ROVIQ is designed to keep the customer journey connected as responsibility moves between diagnostics, service, parts, transport and mobility providers.</p><div class="roviq-tow-feature"><div class="roviq-tow-image">${mediaFull("/images/Roviq Station_ Tow and Parts Hub.png","Roviq tow truck and vehicle transport handoff")}</div><div><span class="eyebrow">Vehicle transport &amp; towing</span><h3>Transport becomes part of the service journey.</h3><p>When a vehicle needs to move, the handoff can remain connected to the surrounding diagnostic, repair and customer experience instead of becoming a separate dead end.</p></div></div></div></section>

<section class="section section--cream-alt" id="mobility"><div class="container"><span class="eyebrow">Mobility</span><h2>Support the customer while the vehicle is being serviced.</h2><p class="lead">ROVIQ’s mobility layer addresses the practical gap between handing over a vehicle and getting it back.</p><div class="grid grid--3"><div class="card card--accent-teal"><h3>Replacement mobility</h3><p>Connect customers to appropriate temporary mobility options when available.</p></div><div class="card card--accent-gold"><h3>Pickup & return</h3><p>Coordinate vehicle movement where a service journey requires it.</p></div><div class="card card--accent-navy"><h3>One journey</h3><p>Keep mobility connected to the underlying service event instead of treating it as a separate transaction.</p></div></div></div></section>

<section class="section"><div class="container"><span class="eyebrow">Capacity network</span><h2>Connect existing automotive capacity instead of owning all of it.</h2><p class="lead">ROVIQ is designed as an asset-light coordination layer linking available service, diagnostic, parts, towing and mobility capacity across participating businesses.</p><p>The public site intentionally does not disclose matching formulas, scoring weights, partner-ranking rules or internal routing logic.</p></div></section>

<section class="section section--cream-alt"><div class="container"><span class="eyebrow">Parts & fulfilment</span><h2>Parts become part of the coordinated service journey.</h2><p class="lead">Parts vendors can connect to active service needs so the customer, shop and vehicle remain tied to the same overall journey.</p><p>ROVIQ’s public positioning describes the participant role only; supplier selection methods, inventory logic and commercial terms remain private.</p></div></section>

<section class="section"><div class="container"><span class="eyebrow">Partners</span><h2>Built for the businesses already serving vehicles.</h2><div class="grid grid--3">${PARTNER_TYPES.map((p)=>`<div class="card card--accent-${p.accent}"><h3>${p.title}</h3><p>${escapeHtml(p.body)}</p><a href="/contact" class="btn btn--outline" style="margin-top:.75rem;font-size:.85rem;padding:.5rem .9rem;">${p.cta} &rarr;</a></div>`).join("\n")}</div></div></section>

<section class="section section--navy"><div class="container"><span class="eyebrow">Physical + digital</span><h2>ROVIQ Station extends the platform into the real world.</h2><p class="lead">ROVIQ Station is the physical expression of the same ecosystem: fuel, charging, food, retail, vehicle care and selected automotive service handoffs brought together in one branded hub.</p><a href="/station" class="btn btn--outline" style="margin-top:1rem;">Explore ROVIQ Station &rarr;</a></div></section>

<section class="section section--cream-alt"><div class="container"><span class="eyebrow">Public architecture</span><h2>Enough to understand the system. Not enough to copy it.</h2><p class="lead">The public site describes participant roles, customer value, product direction and ecosystem structure. Matching algorithms, scoring weights, internal decision rules, partner-routing logic, proprietary data models, private financial information and detailed unit economics remain private.</p></div></section>

<section class="section"><div class="container"><span class="eyebrow">Get involved</span><h2>Partnership, investment and pilot conversations.</h2><p>ROVIQ is actively developing the platform and partner network. For deeper technical, commercial or investment materials, contact the team directly.</p><a href="/contact" class="btn btn--gold" style="margin-top:1rem;">Contact ROVIQ &rarr;</a></div></section>
`;
}
